### ISSUE TITLE
Need Sound suggestion

### ISSUE THREAD

**Issue by FBoucher** [FBoucher/CloudBot#23]
SO the chat bot can play sounds... WHat would you like?
add it in the comment

**Comment by Demb00** [comment]
https://www.youtube.com/watch?v=nDAfnDnT2gA

**Comment by FBoucher** [comment]
I like that one! 
Thanks @Demb00 I will add it!

**Comment by FBoucher** [comment]
@Demb00 new command `!knock` those just than now!
thank you again for the suggestion. 
![bitmoji](https://sdk.bitmoji.com/render/panel/34eeb21c-77de-4d56-a732-d70f83746f26-1d2dd36b-6b40-4c19-aa4b-00c0c130b480-v1.png?transparent=1&palette=1&width=246)
