### ISSUE TITLE
Need a friendly name for the bot... suggestion?

### ISSUE THREAD

**Issue by FBoucher** [FBoucher/CloudBot#24]
We need a name for that bot
![cloudbot_logo](https://user-images.githubusercontent.com/2404846/89650169-fcb71000-d88f-11ea-999a-b1f23e981af5.png)

**Comment by FBoucher** [comment]
I will call it CB until we found something better.

**Comment by DavidVavilov** [comment]
Cloudy?

**Comment by hasiblolic** [comment]
Nimbo - like nimbostratus clouds
Alto - altostratus clouds
Cumulo - cumulonimbus clouds

Other names
Arlo
Otis
Watson
Huck
Fitz
York
Zane
Nico

**Comment by FBoucher** [comment]
Thank you for the suggestions @hasiblolic.
We will make people vote on the stream.

**Comment by FBoucher** [comment]
Let's close this one since I've been calling it Ceebee for so long.
