### ISSUE TITLE
The 'Phrakberg' stat

### ISSUE THREAD

**Issue by surlydev** [FBoucher/CloudBot#8]
As well as the bot keeping track of how many times someone joins a game with !drop the bot should track how often the player lands ON target.

**Comment by FBoucher** [comment]
![bitmoji](https://sdk.bitmoji.com/render/panel/c9fd5973-c9eb-4a54-bfc8-9f8ff7955c3a-1d2dd36b-6b40-4c19-aa4b-00c0c130b480-v1.png?transparent=1&palette=1&width=246)
